services:
  backend:
    image: ghcr.io/apx-group/apx-web:latest
    container_name: apx-backend
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - FRONTEND_DIR=/app/frontend/dist
      - UPLOAD_DIR=/app/uploads
      - SMTP_PORT=${SMTP_PORT:-587}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin1234}
    volumes:
      - ../../public/uploads:/app/uploads
    ports:
      - "80:8080"
