FROM node:20-alpine AS frontend-builder

WORKDIR /frontend
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM linuxserver/nginx:latest
COPY --from=frontend-builder /frontend/dist /config/www
